<?php

namespace OC\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

	public function getApplicationsWithAdvert($limit){
		$qb=$this->createQueryBuilder('a')
				->leftJoin('a.advert', 'advert')
				->addSelect('advert') ; 

		$qb->setMaxResult($limit) ; 

		return $qb->getQuery()->getResult() ; 
	}
}
